version: "2"
services: 
  db: 
    build: "./Database/"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: ussd
      MYSQL_USER: root
      MYSQL_PASSWORD: ''    

  ussd: 
    build: "."
    command: "/usr/bin/hhvm -m server -p 6500"
    depends_on: 
    ports: 
      - "6500:6500"
    restart: always


