version: "2"
services: 
  db: 
    environment:
      MYSQL_ROOT_PASSWORD: ussd
      MYSQL_DATABASE: ussd
      MYSQL_USER: root
      MYSQL_PASSWORD: ussd  
    build: "./Database/"
    restart: always        

  ussd: 
    build: "."
    command: "/usr/bin/hhvm -m server -p 6500"
    depends_on: 
      - db  
    environment:  
      USSD_DB_HOST: "db:3306"
      USSD_DB_PASSWORD: ussd
      USSD_DB_USER: ussd
    ports: 
      - "6500:6500"
    restart: always


